### ISSUE TITLE
The Azim Steppe

### ISSUE THREAD

**Issue by RytoEX** [getignited/xivcurrents#2]
Current 3 and Current 4 have the same description.  As far as I can tell, Current 3 is the incorrect one of the two.  Current 3's coordinates are correct, it is just the description that is incorrect.

**Comment by LiteMorgan** [comment]
I just spotted this earlier actually, but thank you for raising a ticket! I'll get that fixed up.

**Comment by LiteMorgan** [comment]
Current 3 is now corrected and live!
