### ISSUE TITLE
Purple Flame, Purple Flame (Lv. 51)

### ISSUE THREAD

**Issue by ghost** [getignited/xivcurrents#3]
The Dravanian Forelands - Mourn in Passing (Lv. 53)
X: 0, Y: 0, Z: 0 is not correct.

i can not select it on map

**Comment by fabioqcorreia** [comment]
Sent a pull request to fix this. Let's wait! 👍

**Comment by LiteMorgan** [comment]
Apologies folks, away from my machine at the moment! Unfortunately, between 3.2 and 3.3 SE changed a tonne of the quests and locations for Heavensward Aether Currents, so they've all been a bit muddled.

If you have a confirmed location with X,Y,Z co-ords then that would be really useful. :)

**Comment by fabioqcorreia** [comment]
This is where my pull request was based on:
Purple Flame, Purple Flame - http://na.finalfantasyxiv.com/lodestone/playguide/db/quest/567d11de439/
Mourn in Passing - http://na.finalfantasyxiv.com/lodestone/playguide/db/quest/6c61b66982e/

Just check out the pull request I sent to you, I've added the coordinates.

**Comment by LiteMorgan** [comment]
This has been merged in. Thanks for the help! :)
