### ISSUE TITLE
Heavensward Confirmations

### ISSUE THREAD

**Issue by mxygem** [getignited/xivcurrents#5]
Checking in to see if there are any particular Heavensward nodes/zones that still need to be verified? I just checked a few in The Dravanian Forelands and they helped me finish off the zone. Unfortunately, I didn't track specifically which ones I verified in that run but can for others. 

Would a PR with inline comments above particular currents that have been verified be acceptable?

**Comment by LiteMorgan** [comment]
Hey, so sorry I didn't respond to this sooner. Email has been on the fritz for the past two weeks >__<

If this is something you'd still be willing to help with, that would be brilliant! I think most of the quest based ones are all correct, it's just the ones free floating around the world (especially where SE might have moved them!).

**Comment by mxygem** [comment]
Oh haaaaay. So far the ones that I've been able to verify (because I hadn't already got them) have been accurate. I had actually started taking a number of screenshots of the map, LOS of currents (so that a user could see what it looks like in-game), etc but stopped after closing the ticket. >.< 

I'm not sure if you'd like to expand the feature set to include images at all? I figure you're wanting to design the page to be fast and lightweight so I was thinking of only loading an image if a user clicked on it? 

Lastly, where are you wanting the URL fields to point to?

**Comment by LiteMorgan** [comment]
URLs were going to point to images initially! I managed to get snaps of all the Stormblood ones (save for one of the early ones in The Fringes), but had second thoughts due to some of the shots being generally quite bad - somehow I only managed to find Currents at night!

And yes, likewise. Keep the bulk of the site to load only the data, and then lazyload in the required image when the link is clicked on (I'd probably use a lightbox style feature for this).

**Comment by mxygem** [comment]
Glad we're on the same page. haha. Did you do any capping of the map? Do you care about that give we have coords?

I wish I had started this before I started running through HW. >.<

**Comment by LiteMorgan** [comment]
When you say capping of the map, what do you mean sorry?

And haha likewise! The plan was to get a Jump Potion a while back, but money has proved an issue for that plan so far!

**Comment by mxygem** [comment]
Np! When verifying points, I had gone through each of them and took a screenshot of the map at a particular zoom level and included a 6x6 square around me standing on the point. (following the map gridlines) I'm at work currently so I can't share an example.

**Comment by LiteMorgan** [comment]
Yeah, I’d be interested to see how that looks!

I didn’t grab any shots of the map itself, just the co-ords from standing directly in the centre of it! My plan was to grab some of the HQ map assets that are available and build a system to plot the Currents correctly on there, assuming I could get numbers and such working correctly. Still just an idea, at the moment though!
